### ISSUE TITLE
problems with utf8

### ISSUE THREAD

**Issue by fedeinthemix** [ashinn/irregex#13]
Hi,

I've compiled irregex 0.9.4 with Chez Scheme 9.4. I run the test suite and all tests do pass, but the ones in test-irregex-utf8.scm.

I'm just learning SRE, but, if I understand correctly, the following example should match:
(irregex-search (irregex `(: "fede" (~ "Λ") "!") 'utf8) "fedeλ!")
=> #f

Is this wrong? Chez Scheme seems to handle utf8 pretty well.

Thanks you for sharing your code!

**Comment by ashinn** [comment]
The utf8 option is only for implementations that don't already support Unicode, treating strings as byte vectors.  Just removing the 'utf8 should work.

**Comment by fedeinthemix** [comment]
The example I gave does indeed work without 'urf8. I'm still not able to
make the tests in 'test-irregex-utf8.scm' work. Here an example:

(irregex-search "(?u:<..>)" "<漢字>")
=> #f

Are those test supposed to work?

Thank you for your help!

**Comment by ashinn** [comment]
The "(?u:...)" syntax is just another way of representing 'utf8, and is expected to fail on an implementation with native unicode support.

**Comment by fedeinthemix** [comment]
Thanks for the clarification!
