### ISSUE TITLE
Replacements of positive lookbehinds only replace first match

### ISSUE THREAD

**Issue by sjamaan** [ashinn/irregex#21]
Reported on [chicken-users](https://lists.nongnu.org/archive/html/chicken-users/2020-07/msg00005.html):

`irregex-replace/all` only replaces first match when negative lookbehinds are involved

example:

the following regexp should replace any letter a preceded by x, y, or z

problematic code

```
(irregex-replace/all "(?<=[xyz])a"     "xa ya za"  "-")
; or 
(irregex-replace/all '(: (look-behind (or "x" "y" "z")) "a")   "xa ya za"  "-")
```

should return `"x- y- z-"` BUT actually returns `"x- ya za"`

**Comment by masukomi** [comment]
That was me in chicken-users. Holler if there's anything else you need from me. I should probably note that as far as i can tell this works fine with look-aheads, just not look-_behinds_.

**Comment by ashinn** [comment]
Fixed, thanks!
