### ISSUE TITLE
Empty matches on replace/all

### ISSUE THREAD

**Issue by snan** [ashinn/irregex#24]
(irregex-replace/all
     (irregex '(: bos (* whitespace)))
     "any gosh darn string" "")

    ⇒ "aany gosh darn string"

With a + instead of a kleenstar it works.

**Comment by ashinn** [comment]
0.9.7 fixed some corner cases involving empty matches, causing this regression.  It's surprisingly tricky to get these all right - I'm half tempted to just throw errors on empty matches :(

**Comment by snan** [comment]
Please do not throw errors on empty matches!

**Comment by ashinn** [comment]
I'm just grumbling and kicking myself for fixing the symptoms of the empty matches previously instead of the root cause.

**Comment by snan** [comment]
What I did for loop detection was to stop when we were string=? to the previous iter. That has turned out to be super expensive though.

**Comment by ashinn** [comment]
Just use irregex-fold for iteration, it does the work for you.

**Comment by snan** [comment]
I do use irregex-fold in another place in the code. The case where I used string=? for loop detection was for recursive re-matching from the start of the string. I.e. `(strse "aaaaaaaah!" "aa" "a" #t)` ⇒ "ah!" This isn't something irregex-fold is set up to do since it uses consecutive matching on the original string. Also, irregex-fold/fast isn't exported as far as I could tell so the way to use it is to use replace/all, which is what my "aaaaaah" thing does: calls replace/all again and again until it's satisfied.
