### ISSUE TITLE
bol overlaps with newline

### ISSUE THREAD

**Issue by snan** [ashinn/irregex#25]
This is either an irregex pro tip or a bug:

(: bol "blablabla" newline) will create overlaps if there are sequential matches. Capturing the newline there borks up the subsequent bol. It only works if the matches are non-sequential.

(: newline "blablabla" eol) doesn't have that problem at all.

(Now, the reason to capture newline instead of just using bol and eol is so that we can replace with "" to remove theh line entirely.)

Note that the (: newline "blablabla" eol) can't match the first line of the text. So this pro tip only works when you know you don't need to do it on the first line of text in a multiline string. 

Not sure if there is an even better pro tip / best practice for this particular use case.

**Comment by snan** [comment]
Btw, it is to irregex' credit that this is way faster than string-splitting the string into lines and working on individual lines.♥

**Comment by ashinn** [comment]
Sorry for the delay, I haven't forgotten this, just haven't had time to look into it, please be patient.

**Comment by ashinn** [comment]
It's an inconsistency with the chunking and iteration logic.  While extracting, do we consider successive searches after the first match to be part of the same string or part of a new string which is conceptually the tail substring of the original?

If the former, the `bol` check should see the preceding newline and pass.  If the latter, the `bol` check should see that it is the start of a new string and pass.  Unfortunately, we make these two checks inconsistently such that they both fail.

It's easy enough to fix and I've verified this, I just want to remind myself why the iteration is creating new chunks and whether that is the right thing to begin with.

**Comment by ashinn** [comment]
Actually I had made the same fix for `bow` earlier and just forgot to apply it to `bol`.

**Comment by sjamaan** [comment]
Looks like the fix broke a test:

```
    (irregex-replace/all 'bol "Line 1\nLine 2" "*") .................. [ FAIL]
        expected "*Line 1\n*Line 2" but got "*Line 1\n**Line 2"
```

**Comment by ashinn** [comment]
Oops, that'll teach me to remember to disable TEST_FILTERs when testing before the release...
