### ISSUE TITLE
Empty concat causes vector error

### ISSUE THREAD

**Issue by jbclements** [ashinn/irregex#26]
Using an empty concatenation as part of an SRE pattern can cause an out-of-range vector reference. 

`(irregex-search '(or (:) "was") "abc")`

```
pajaro2:/tmp/irregex (git)-[master]- clements> scheme
Chez Scheme Version 9.5.4
Copyright 1984-2020 Cisco Systems, Inc.

> (import (irregex))
> (irregex-search '(or (:) "was") "abc")
Exception in vector-ref: 3 is not a valid index for #(0 0)
Type (debug) to enter the debugger.
>
```

**Comment by ashinn** [comment]
Wow... how did you even find this example? :)

We can rewrite these cases to `(? (or "was"))` but I want to figure out why this confuses the number of states.

**Comment by jbclements** [comment]
Well, as you can imagine, I was using Z3 to construct a full proof of correctness of the code...

Uh, no. It was basically just stupidity and/or luck. I think I wasn't yet sure how to specify an empty match.

With that said, I suppose a simple tester that enumerates all small SREs might well have found it. XSmith, maybe? Dunno.

**Comment by sjamaan** [comment]
It looks like somehow the states corresponding to the second `or` argument get entirely dropped: 

```
> (sre->nfa '(or (:) "was") 0)
#(0 -1 () () () ((3 . #f) (0 . #f)) () ())
```

**Comment by sjamaan** [comment]
OK, turned out to be a pretty simple fix

**Comment by sjamaan** [comment]
Could you review it @ashinn, just to make sure it is indeed the correct fix?
