### ISSUE TITLE
Missing tests for result of string-scan-char

### ISSUE THREAD

**Issue by feeley** [ashinn/irregex#47]
There are a few places in `irregex.scm` where the result of `string-scan-char` is assumed to be a number. However, in some cases `string-scan-char` can return `#f`. The code is missing explicit checks for this, for example:

```
                     ((char-numeric? (string-ref str (+ i 3)))
                      (let* ((j (string-scan-char str #\) (+ i 3)))
                             (n (and j (string->number (substring str (+ i 3) j))))) ;; added (and j ...
                        (if (not n)
                            (error "invalid conditional reference" str)
```

This issue is triggered by the following unit test in `test-irregex-from-gauche.scm`:

```
(test-error (irregex "()((?(1"))
```

When the code is interpreted with Gambit, an error is caught, but it is a type error on the third parameter of `substring`. When the code is compiled in unsafe mode, that unit test crashes the program.

**Comment by ashinn** [comment]
Thanks for the report!  This is technically valid but lazy code, because we would throw an error in these cases anyway, just the resulting error is hard to understand.  Let me clean it up.

**Comment by feeley** [comment]
Thanks!

I guess it is a philosophical question whether this is a bug or not. I classify it as a bug in the library because the library should not assume the host Scheme system checks for errors, in this case the call `(substring "..." 0 #f)`. So it is the library's functions responsibility to detect errors in the parameters it receives. But I can understand the other way around too (i.e. Scheme is a safe language and it is its responsibility to detect errors).
