### ISSUE TITLE
Obtain regexp source string from compiled regexp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ashinn/irregex#5]
```
Hello.

Please, add functions which retrieve regexp source string and its options:

> (irregex-src (irregex "apple")) => "apple"
> (irregex-opt (irregex "apple" 'i 'm)) => (i m)

Thanks.
```

Original issue reported on code.google.com by `yarsanuk...@gmail.com` on 5 Sep 2010 at 4:42

**Comment by sjamaan** [comment]
@ashinn shall we just close this ticket? I don't see the value in lugging the source string around inside the regex. Also, there's no guarantee the source was even a string in the first place.

**Comment by ashinn** [comment]
sgtm
